# 1. On part de l'image officielle Airflow (version stable récente)
FROM apache/airflow:2.9.1-python3.11

# 2. On passe en utilisateur "root" pour installer des paquets système si besoin (optionnel mais prudent)
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 3. On repasse en utilisateur "airflow" pour installer les librairies Python
USER airflow

# 4. On copie tes requirements
COPY requirements.txt /requirements.txt

# 5. On installe tes librairies DANS Airflow
RUN pip install --no-cache-dir -r /requirements.txt
